server:
  port: 8111

spring:
  datasource:
    name: songs
    url: jdbc:mysql://39.96.86.4:3308/community?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    #    url: jdbc:p6spy:mysql://localhost:3306/songs?characterEncoding=utf-8&useSSL=false
    username: root
    password: kaikai
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: warn
    com.fehead.songs.dao: trace
  pattern:
    console: '%p%m%n'
