server:
  port: 8111

spring:
  datasource:
    name: songs
    url: jdbc:mysql://39.96.86.4:3308/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    #    url: jdbc:p6spy:mysql://localhost:3306/songs?characterEncoding=utf-8&useSSL=false
    username: root
    password: kaikai
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 59.110.158.93 # Redis的服务地址
    port: 6379 # Redis的服务端口
    password: kaikaikai
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲链接
    timeout: 1200 # 连接池的超时时间（毫秒）

#logging:
#  level:
#    root: warn
#    com.fehead.community.mapper: trace
#  pattern:
#    console: '%p%m%n'

ftp:
  host: 59.110.158.93
  userName: root
  password: zhengui3.
  port: 22
  rootPath: /home/ftpadmin/health/images
  img:
    url: http://59.110.158.93:4545      # ftp.img.url 可以不添加，这里只是为了上传文件成功后返回文件路径


